project_id = "ckehjrxronooagpdruyr"

[functions.chat]
verify_jwt = false

[functions.note-assistant]
verify_jwt = true

[functions.format-note]
verify_jwt = true

[functions.search-notes]
verify_jwt = true

[functions.webauthn-challenge]
verify_jwt = false

[functions.webauthn-verify]
verify_jwt = false